# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20160714_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Reviewtags',
            new_name='Tags',
        ),
    ]
