# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_followers_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Project'),
        ),
    ]
